In [1]:
import math as m
import numpy as np
import matplotlib.pyplot as plt

In [8]:
N=100
U=np.zeros([N,N])

for i in range(0,N):
    U[0][i]=100.0
U

array([[100., 100., 100., ..., 100., 100., 100.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

# Using Gauss Jacobi method

In [3]:
h=0.01
precision=1.0
iteration=0
while (precision)>h:
    iteration+=1                     
    T=np.zeros([N,N])         
    for i in range(0,N):
        for j in range(0,N):
            if i==0 or i==N-1 or j==0 or j==N-1:
                T[i][j]=U[i][j]          #BC 
            else:
                T[i][j]=(U[i+1][j]+U[i-1][j]+U[i][j+1]+U[i][j-1])/4   
    precision=np.max(np.abs(T-U))
    U=T   
print("No. of iterations :",iteration)
print("Error in potential :",precision)

No. of iterations : 1897
Error in potential : 0.009998358245198347


In [4]:
T

array([[1.00000000e+02, 1.00000000e+02, 1.00000000e+02, ...,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02],
       [0.00000000e+00, 4.99663928e+01, 6.96980749e+01, ...,
        6.96980749e+01, 4.99663928e+01, 0.00000000e+00],
       [0.00000000e+00, 3.01675663e+01, 4.98657110e+01, ...,
        4.98657110e+01, 3.01675663e+01, 0.00000000e+00],
       ...,
       [0.00000000e+00, 1.68364012e-03, 3.36497536e-03, ...,
        3.36497536e-03, 1.68364012e-03, 0.00000000e+00],
       [0.00000000e+00, 8.37514187e-04, 1.67388410e-03, ...,
        1.67388410e-03, 8.37514187e-04, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

# Using Gauss Seidel

In [6]:
# N=10
# U=np.zeros([N,N])
# for i in range(0,N):
#     for j in range(0,N):
#         if i==0:
#             U[i][j]=100    
# print(U)

In [7]:
# h=0.01
# precision=1.0
# iteration=0
# while (precision)>h:
#     iteration+=1
#     T=U
#     for i in range(1,N-1):
#         for j in range(1,N-1):          
#             T[i][j]=(U[i+1][j]+U[i-1][j]+U[i][j+1]+U[i][j-1])/4
#     precision=np.max(np.abs(T-U))
# print(iteration)
# print(T)

In [5]:
# x=np.linspace(0,1,N)
# y=np.linspace(0,1,N)
# X,Y=np.meshgrid(x,y)
# plt.contourf(X,Y,U)
# plt.colorbar().set_label("Electric potential")

In [5]:
# X=np.linspace(0,1,N)
# Y=np.linspace(0,1,N)
  
# plt.contourf(X,Y,U,levels=np.linspace(0,100,10))
# plt.colorbar().set_label("Electric potential")

HEAT EQUATION

In [8]:
N=100
U=np.zeros([N,N])
for i in range(0,N):
    U[0][i]=100.0
U

array([[100., 100., 100., ..., 100., 100., 100.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [20]:
N=100
U=np.zeros([N,N])
for i in range(0,N):
    U[0][i]=100.0
U[0][0]=0
U[0][N-1]=0
U

array([[  0., 100., 100., ..., 100., 100.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,   0.,   0.,   0.]])

In [23]:
h=0.01
precision=1.0
iteration=0
g=2
while (precision)>h:
    iteration+=1                     
    T=np.zeros([N,N])         
    for i in range(0,N):
        for j in range(0,N):
            if i==0 or i==N-1 or j==0 or j==N-1:
                T[i][j]=U[i][j]          
            else:
                T[i][j+1]=(g*U[i-1][j]+(1-2*g)*U[i][j]+g*U[i][j+1]+U[i+1][j+1])
    precision=np.max(np.abs(T-U))
    U=T   
print("No. of iterations :",iteration)

No. of iterations : 514


C:\Users\pankh\AppData\Local\Temp\ipykernel_36220\2861867200.py:13: RuntimeWarning: overflow encountered in double_scalars
  T[i][j+1]=(g*U[i-1][j]+(1-2*g)*U[i][j]+g*U[i][j+1]+U[i+1][j+1])
C:\Users\pankh\AppData\Local\Temp\ipykernel_36220\2861867200.py:13: RuntimeWarning: invalid value encountered in double_scalars
  T[i][j+1]=(g*U[i-1][j]+(1-2*g)*U[i][j]+g*U[i][j+1]+U[i+1][j+1])
C:\Users\pankh\AppData\Local\Temp\ipykernel_36220\2861867200.py:14: RuntimeWarning: invalid value encountered in subtract
  precision=np.max(np.abs(T-U))


In [24]:
print(U)

[[ 0.00000000e+000  1.00000000e+002  1.00000000e+002 ...  1.00000000e+002
   1.00000000e+002  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  1.60893695e+157 ... -1.58364173e+308
               inf  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -1.06962167e+308
              -inf  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   1.97150697e+263  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]]


In [5]:
# N=100
# U=np.full([N,N],7.0)
# for i in range(0,N):
#     for j in range(0,N):
#         if i==0:
#             U[i][j]=100.0 
#         elif i==N-1 or j==0 or j==N-1:
#             U[i][j]=0.0
# U

Seidel

In [3]:
tolerance=0.01
precision=1
iteration=0
while(precision>tolerance):
    iteration+=1
    T=np.array(U)
    for i in range(1,N-1):
        for j in range(1,N-1):
            U[i][j]=(U[i+1][j]+U[i-1][j]+U[i][j+1]+U[i][j-1])/4
    precision=np.max(np.abs(T-U))
print("No. of iterations :",iteration)
print("Error in potential :",precision)

No. of iterations : 1451
Error in potential : 0.009989454544509613


In [4]:
T

array([[1.00000000e+02, 1.00000000e+02, 1.00000000e+02, ...,
        1.00000000e+02, 1.00000000e+02, 1.00000000e+02],
       [0.00000000e+00, 4.99773040e+01, 6.97198997e+01, ...,
        6.97210831e+01, 4.99779100e+01, 0.00000000e+00],
       [0.00000000e+00, 3.01893745e+01, 4.99093321e+01, ...,
        4.99116949e+01, 3.01905844e+01, 0.00000000e+00],
       ...,
       [0.00000000e+00, 6.97623917e-03, 1.39554114e-02, ...,
        1.48900384e-02, 7.45473918e-03, 0.00000000e+00],
       [0.00000000e+00, 3.48335149e-03, 6.96817405e-03, ...,
        7.43531827e-03, 3.72251436e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])